### ISSUE TITLE
Theme no longer works with new vencord update.

### ISSUE THREAD

**Issue by ExpAntique** [RockESV/Eris#9] opened 2024-02-28 14:48 UTC
Turning theme on or off does nothing.

**Comment by gasekun** [comment] 2024-02-28 15:47
Edit the theme on this:
```css
/**
 * @name Eris
 * @author Rock#5429
 * @version 1.4
 * @description A darker, cooler, classier look for Discord.
 * @source https://github.com/RockESV/Eris
*/

@import url("https://raw.githubusercontent.com/RockESV/Eris/main/src/eris-whitney-font.css");
@import url("https://raw.githubusercontent.com/RockESV/Eris/main/src/eris-logos-pfps.css");

:root, .theme-dark, .theme-light {
    --font-primary: 'Whitney';
    --font-display: 'Whitney';
    --brand-experiment: hsl(227, 58%, 65%);
    --brand-500: var(--brand-experiment);
    --brand-experiment-560: hsl(227, 58%, 67.5%);
    --brand-experiment-600: hsl(227, 58%, 70%);
    --background-secondary: var(--background-primary);
    --background-secondary-alt: var(--background-primary);
    --background-modifier-selected: var(--background-tertiary);
    --background-floating: var(--background-tertiary);
    --channeltextarea-background: var(--background-tertiary);
    --input-background: var(--background-tertiary);
    --scrollbar-auto-thumb: var(--background-tertiary);
    --scrollbar-auto-track: transparent;
    --scrollbar-thin-thumb: var(--background-tertiary);
    --scrollbar-thin-track: transparent;
    --modal-background: var(--background-primary);
    --modal-footer-background: var(--background-primary);
    --deprecated-card-bg: var(--background-tertiary);
    --deprecated-text-input-border: none;
    --box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.2);
    --elevation-high: var(--box-shadow);
    --elevation-stroke: var(--box-shadow);
    --dark-elevation-border: var(--box-shadow);
    --dark-elevation-high: var(--box-shadow);
    --dark-elevation-low: var(--box-shadow);
    --search-popout-option-fade: transparent;
    --search-popout-option-fade-hover: transparent;
}

.theme-dark {
    --background-primary: #1f2125;
    --background-tertiary: #14161a;
    --text-normal: #ffffff;
    --text-muted: #9b9b9b;
    --channels-default: #b8b8b8;
}

.theme-light {
    --background-primary: #f5f5f5;
    --background-tertiary: #cccccc;
    --channels-default: #1a1a1a;
    --text-normal: #000000;
    --text-muted: #6e6e6e;
}

/* SETTINGS SECTION */

:root .info__755e1 .text-xs-normal__56c35:first-child:before { /* Eris theme information at the bottom of the Settings sections */
	text-transform: none;
    content: "Eris v1.4 by Rock";
	display: block;
}

:root .sidebarRegionScroller__1fa7e { /* Settings sidebar background and selected options color */
    background-color: var(--background-tertiary);
}

.side_b4b3f6 .themed_b957e8.selected__5711d.item__48dda {
    background-color: var(--brand-experiment);
}

.side_b4b3f6 .themed_b957e8.selected__5711d.item__48dda:hover:not(.disabled-1nofHP) {
    background-color: var(--brand-experiment);
}

.accountProfileCard__22589, .bioTextArea_a108c9, .input_d266e7:not(.note_ba0c31 .textarea_c5a7a3, .multiInputField-1zyopx, .note-3TX9O7 .textarea_c5a7a3), .lookFilled__3dba3.select__0eb48, .itemFilled__373d7[aria-checked=true], .feedback__2b8a9 { /* Box shadow for various boxes in Settings */
    box-shadow: var(--box-shadow);
}

:root .footerSeparator-VzAYwb {
    box-shadow: none;
}

.popout_a6e77f, .formNotice__8622e.cardPrimary-3qRT__.card-16VQ8C, .authedApp__51b26, .connection_fff5f6, .connectContainer__8050b, .guilds__66a9b .cardWrapper_bc8d2a, :root .codeRedemptionRedirect_bc7f36, .cameraWrapper__1ee6d, .cardWrapper__09290 .card__3662a { /* Theming for dropdown menu and various cards */
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
    border: none;
}

.option_be8b2e[aria-selected=true]:not(.option_be8b2e.multi__8d15f) { /* Removes background of selected item in dropdown menu */
    background-color: transparent;
}

.connectionHeader__3c82d { /* Theming for Connections section in Settings */
    background: transparent;
}

.connectionList__7b310 {
    grid-gap: 8px;
}

.metadataContainer__7b316, .container-QlmnKJ {
    padding: 0 16px;
    margin: 0;
}

.bd-addon-list .bd-addon-card { /* Theming for BetterDiscord settings section */
    background: var(--background-tertiary);
    box-shadow: var(--box-shadow);
    padding: 0px 16px 16px;
}

.bd-addon-list .bd-addon-header {
    background: transparent;
    padding: 16px 0;
}

.bd-description-wrap, .bd-footer {
    background: var(--background-primary);
}

.bd-description-wrap {
    padding-top: 16px;
    border-radius: 5px 5px 0px 0px;
}

.bd-button:not(.bd-button-danger), .bd-addon-views .bd-view-button.selected {
    background-color: var(--brand-experiment);
}

/* FRIENDS SECTION */

.channel_c21703.container__8759a[aria-posinset="2"] { /* Disables Nitro button in Friends page */
    display: none;
}

.searchBar_e4ea2a .searchBarComponent__22760 { /* Conversartion search box shadow */
    box-shadow: var(--box-shadow);
}

.topPill__0cdf1 .themed_b957e8.selected__5711d.item_e4ca95 { /* Box shadow for selected tab under Friends */
    box-shadow: var(--box-shadow);
}

.topPill__0cdf1 .item_e4ca95 { /* Gives top tabs in Friends enough room for box shadow */
    margin: 8px 8px;
}

.container__11d72 .upperContainer__993ba {
    padding: 4px 0;
}

.container__5c7e7 .container__11d72 {
    padding: 0 8px;
}

.interactive__776ee.selected_d94cf9 { /* Box shadow for selected DM */
    box-shadow: var(--box-shadow);    
}

.topPill__0cdf1 .themed_b957e8.item_e4ca95.selected__5711d:hover:not(.disabled-1nofHP) {
    background-color: var(--background-tertiary);
}

.privateChannels__93473 .scroller__4b984.thin_b1c063.scrollerBase_dc3aa9.fade_ba0fa0 { /* Gives DM list enough room for box shadow to display fully */
    padding-right: 4px !important;
}

.interactive__776ee.selected_d94cf9:hover { /* Fix selected DM color on hover */
    background-color: var(--background-tertiary);
    color: var(--interactive-active);
}

ul.content__23cab[aria-label="Direct Messages"]:nth-child(2) .interactive__776ee.selected_d94cf9, ul.content__23cab[aria-label="Direct Messages"]:nth-child(4) .interactive__776ee.selected_d94cf9 { /* Fix Friends and Shop buttons color weirdness */
    background-color: var(--background-tertiary) !important;
    color: var(--interactive-active) !important;
}

.peopleColumn__51df3 .searchBar_ff8800 { /* Friends search box shadow */
    box-shadow: var(--box-shadow);
}

.nowPlayingColumn_f5023f .itemCard__1f162, :root .outer_a41cf3.active__76f42, :root .outer_a41cf3.interactive__01cfa:hover { /* Theming for Active Now cards */
    background-color: var(--background-tertiary);
    border: none;
    box-shadow: var(--box-shadow);
    margin-top: 16px;
}

.nowPlayingColumn_f5023f .itemCard__1f162 .section_efc22d, :root .inset__0bfb3 { 
    background-color: transparent;
}

.nowPlayingColumn_f5023f .itemCard__1f162 .section_efc22d {
    padding: 12px 0 0 0;
}

.scroller__00e7e { /* Removes divider between Friends and Active Now */
    border-left: none;
}

.root_a28985 { /* User profile modal box shadow */
    box-shadow: var(--box-shadow) !important;
}

.channelTextArea__2e60f.channelTextArea__56a36, .searchBar_e0c60b { /* Message text field and message search bar box shadow */
    box-shadow: var(--box-shadow);
}

.button__4f306.enabled__470f0:hover, .button__66e8c.buttonColor_a6eb73:hover, .withTagAsButton_cc125f:hover { /* Hover background and box shadows on user buttons */
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
}

#popout_9007.layer_ec16dd, .overlayBackground__86b78 { /* Box shadow for user profile popout */
    box-shadow: var(--box-shadow);
}

.userPopoutOuter_d739b2 {   /* Box shadow for own user profile */
    box-shadow: var(--box-shadow);
}

/* CHANNELS */

:root .autocomplete_df266d {   /* Mentions menu background and shadow */ 
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
}

.containerDefault__3187b.selected__3b4cb, .containerDefault__3187b.wrapper__7bcde.modeSelected__487d6 { /* Styling for selected channel or thread */
    box-shadow: var(--box-shadow);
    background-color: var(--background-tertiary);
    margin-left: 0;
    border-left: 4px solid var(--brand-experiment);
    border-radius: 0 4px 4px 0;
    margin-right: 8px;
}

.wrapper__7bcde:hover .link__95dc0 { /* Styling for hovered channels */
    margin-right: 8px;
}

.selected__9800b.container__4f20e .layout_bb8e67 { /* Styling for selected user in channel */
    box-shadow: var(--box-shadow);
    margin-right: 8px;
}

.container__4f20e .layout_bb8e67:hover { /* Box shadow for hovered user in channel */
    margin-right: 8px;
}

.browser_fece63 .header__53b07 { /* Styling for Threads popup */
    background-color: var(--background-primary);
}

.searchBox_ff53b2.container__7712a, .container__6604b:hover {
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
    border: none;
}

.container-3i3IzO, .card-PQEqCK, .submitContainer_b4471d .channelTextArea_c27a51.channelTextArea__56a36, div.container_dbadf5 .wrapper_efe67f { /* Styling for threads preview, first message card, and server invites */
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
}

.jumpToPresentBar__0ff7f .barButtonMain__0f5c6 {  /* Styling for jump to present bar */
    display: none;
}

.jumpToPresentBar__0ff7f {
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
    margin-bottom: 16px;
    padding: 4px;
    border-radius: 8px;
    opacity: 1;
    left: initial;
}

.jumpToPresentBar__0ff7f:active {
    margin-bottom: 15px;
}

:root .spoilerContent__37bfa.hidden_f44e41, .markup_a7e664 pre code { /* Styling for code blocks and spoilers */
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
}

.markup_a7e664 blockquote, .markup_a7e664 pre {
    margin-bottom: 5px;
}

:root .spoilerContent__37bfa.hidden_f44e41:hover {
    background-color: var(--background-modifier-hover);
}

.newMosaicStyle__8d3be .textContainer__709ff, .newMosaicStyle__8d3be .footer__06f4b, .newMosaicStyle__8d3be .codeView__8b1ff, .attachment_f3cf2c { /* Styling for attachments */
    border: none;
    background-color: transparent;
}

.attachmentContentItem_ef9fc2, .wrapperAudio__555ce.newMosaicStyle_fb18b9 {
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
    border-radius: 8px;
    border: none;
}

.hoverButtonGroup__5b423.nonMediaAttachment__30665 {
    outline: none;
    top: 8px;
    right: 8px;
    background-color: transparent;
}

#emoji-picker-tab-panel .searchBar__8f956 { /* Emoji picker search bar */
    box-shadow: var(--box-shadow);
}

.embedFull__8dc21 { /* Styling for embeds */
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
}

.wrapper_c727b6, .reaction_fef95b.reactionMe__98f57 { /* Styling for message buttons and reactions */
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
}

.wrapper_fbbb73 {   /* Box shadow for "Follow to get this channel's updates in your own server." wrapper */
    box-shadow: var(--box-shadow);
}

.header__60bef, .container__10dc7, .scrollerContainer_bf5dbd, .container__7590f { /* Background color for channel browsing page */
    background-color: var(--background-primary) !important;
}

.search__4a09e.container__7712a.medium__0fb5d, .container__7590f .container__6a848, .optionButtonWrapper__4072c  { /* Styling for channel browsing search bar and cards */
    background-color: var(--background-tertiary);
    box-shadow: var(--box-shadow);
    border: none;
}
`

**Comment by ExpAntique** [comment] 2024-02-28 18:01
> Edit the theme on this:
> 
> ```css
> /**
>  * @name Eris
>  * @author Rock#5429
>  * @version 1.4
>  * @description A darker, cooler, classier look for Discord.
>  * @source https://github.com/RockESV/Eris
> */
> 
> @import url("https://raw.githubusercontent.com/RockESV/Eris/main/src/eris-whitney-font.css");
> @import url("https://raw.githubusercontent.com/RockESV/Eris/main/src/eris-logos-pfps.css");
> 
> :root, .theme-dark, .theme-light {
>     --font-primary: 'Whitney';
>     --font-display: 'Whitney';
>     --brand-experiment: hsl(227, 58%, 65%);
>     --brand-500: var(--brand-experiment);
>     --brand-experiment-560: hsl(227, 58%, 67.5%);
>     --brand-experiment-600: hsl(227, 58%, 70%);
>     --background-secondary: var(--background-primary);
>     --background-secondary-alt: var(--background-primary);
>     --background-modifier-selected: var(--background-tertiary);
>     --background-floating: var(--background-tertiary);
>     --channeltextarea-background: var(--background-tertiary);
>     --input-background: var(--background-tertiary);
>     --scrollbar-auto-thumb: var(--background-tertiary);
>     --scrollbar-auto-track: transparent;
>     --scrollbar-thin-thumb: var(--background-tertiary);
>     --scrollbar-thin-track: transparent;
>     --modal-background: var(--background-primary);
>     --modal-footer-background: var(--background-primary);
>     --deprecated-card-bg: var(--background-tertiary);
>     --deprecated-text-input-border: none;
>     --box-shadow: 4px 4px 8px rgba(0, 0, 0, 0.2);
>     --elevation-high: var(--box-shadow);
>     --elevation-stroke: var(--box-shadow);
>     --dark-elevation-border: var(--box-shadow);
>     --dark-elevation-high: var(--box-shadow);
>     --dark-elevation-low: var(--box-shadow);
>     --search-popout-option-fade: transparent;
>     --search-popout-option-fade-hover: transparent;
> }
> 
> .theme-dark {
>     --background-primary: #1f2125;
>     --background-tertiary: #14161a;
>     --text-normal: #ffffff;
>     --text-muted: #9b9b9b;
>     --channels-default: #b8b8b8;
> }
> 
> .theme-light {
>     --background-primary: #f5f5f5;
>     --background-tertiary: #cccccc;
>     --channels-default: #1a1a1a;
>     --text-normal: #000000;
>     --text-muted: #6e6e6e;
> }
> 
> /* SETTINGS SECTION */
> 
> :root .info__755e1 .text-xs-normal__56c35:first-child:before { /* Eris theme information at the bottom of the Settings sections */
> 	text-transform: none;
>     content: "Eris v1.4 by Rock";
> 	display: block;
> }
> 
> :root .sidebarRegionScroller__1fa7e { /* Settings sidebar background and selected options color */
>     background-color: var(--background-tertiary);
> }
> 
> .side_b4b3f6 .themed_b957e8.selected__5711d.item__48dda {
>     background-color: var(--brand-experiment);
> }
> 
> .side_b4b3f6 .themed_b957e8.selected__5711d.item__48dda:hover:not(.disabled-1nofHP) {
>     background-color: var(--brand-experiment);
> }
> 
> .accountProfileCard__22589, .bioTextArea_a108c9, .input_d266e7:not(.note_ba0c31 .textarea_c5a7a3, .multiInputField-1zyopx, .note-3TX9O7 .textarea_c5a7a3), .lookFilled__3dba3.select__0eb48, .itemFilled__373d7[aria-checked=true], .feedback__2b8a9 { /* Box shadow for various boxes in Settings */
>     box-shadow: var(--box-shadow);
> }
> 
> :root .footerSeparator-VzAYwb {
>     box-shadow: none;
> }
> 
> .popout_a6e77f, .formNotice__8622e.cardPrimary-3qRT__.card-16VQ8C, .authedApp__51b26, .connection_fff5f6, .connectContainer__8050b, .guilds__66a9b .cardWrapper_bc8d2a, :root .codeRedemptionRedirect_bc7f36, .cameraWrapper__1ee6d, .cardWrapper__09290 .card__3662a { /* Theming for dropdown menu and various cards */
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
>     border: none;
> }
> 
> .option_be8b2e[aria-selected=true]:not(.option_be8b2e.multi__8d15f) { /* Removes background of selected item in dropdown menu */
>     background-color: transparent;
> }
> 
> .connectionHeader__3c82d { /* Theming for Connections section in Settings */
>     background: transparent;
> }
> 
> .connectionList__7b310 {
>     grid-gap: 8px;
> }
> 
> .metadataContainer__7b316, .container-QlmnKJ {
>     padding: 0 16px;
>     margin: 0;
> }
> 
> .bd-addon-list .bd-addon-card { /* Theming for BetterDiscord settings section */
>     background: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
>     padding: 0px 16px 16px;
> }
> 
> .bd-addon-list .bd-addon-header {
>     background: transparent;
>     padding: 16px 0;
> }
> 
> .bd-description-wrap, .bd-footer {
>     background: var(--background-primary);
> }
> 
> .bd-description-wrap {
>     padding-top: 16px;
>     border-radius: 5px 5px 0px 0px;
> }
> 
> .bd-button:not(.bd-button-danger), .bd-addon-views .bd-view-button.selected {
>     background-color: var(--brand-experiment);
> }
> 
> /* FRIENDS SECTION */
> 
> .channel_c21703.container__8759a[aria-posinset="2"] { /* Disables Nitro button in Friends page */
>     display: none;
> }
> 
> .searchBar_e4ea2a .searchBarComponent__22760 { /* Conversartion search box shadow */
>     box-shadow: var(--box-shadow);
> }
> 
> .topPill__0cdf1 .themed_b957e8.selected__5711d.item_e4ca95 { /* Box shadow for selected tab under Friends */
>     box-shadow: var(--box-shadow);
> }
> 
> .topPill__0cdf1 .item_e4ca95 { /* Gives top tabs in Friends enough room for box shadow */
>     margin: 8px 8px;
> }
> 
> .container__11d72 .upperContainer__993ba {
>     padding: 4px 0;
> }
> 
> .container__5c7e7 .container__11d72 {
>     padding: 0 8px;
> }
> 
> .interactive__776ee.selected_d94cf9 { /* Box shadow for selected DM */
>     box-shadow: var(--box-shadow);    
> }
> 
> .topPill__0cdf1 .themed_b957e8.item_e4ca95.selected__5711d:hover:not(.disabled-1nofHP) {
>     background-color: var(--background-tertiary);
> }
> 
> .privateChannels__93473 .scroller__4b984.thin_b1c063.scrollerBase_dc3aa9.fade_ba0fa0 { /* Gives DM list enough room for box shadow to display fully */
>     padding-right: 4px !important;
> }
> 
> .interactive__776ee.selected_d94cf9:hover { /* Fix selected DM color on hover */
>     background-color: var(--background-tertiary);
>     color: var(--interactive-active);
> }
> 
> ul.content__23cab[aria-label="Direct Messages"]:nth-child(2) .interactive__776ee.selected_d94cf9, ul.content__23cab[aria-label="Direct Messages"]:nth-child(4) .interactive__776ee.selected_d94cf9 { /* Fix Friends and Shop buttons color weirdness */
>     background-color: var(--background-tertiary) !important;
>     color: var(--interactive-active) !important;
> }
> 
> .peopleColumn__51df3 .searchBar_ff8800 { /* Friends search box shadow */
>     box-shadow: var(--box-shadow);
> }
> 
> .nowPlayingColumn_f5023f .itemCard__1f162, :root .outer_a41cf3.active__76f42, :root .outer_a41cf3.interactive__01cfa:hover { /* Theming for Active Now cards */
>     background-color: var(--background-tertiary);
>     border: none;
>     box-shadow: var(--box-shadow);
>     margin-top: 16px;
> }
> 
> .nowPlayingColumn_f5023f .itemCard__1f162 .section_efc22d, :root .inset__0bfb3 { 
>     background-color: transparent;
> }
> 
> .nowPlayingColumn_f5023f .itemCard__1f162 .section_efc22d {
>     padding: 12px 0 0 0;
> }
> 
> .scroller__00e7e { /* Removes divider between Friends and Active Now */
>     border-left: none;
> }
> 
> .root_a28985 { /* User profile modal box shadow */
>     box-shadow: var(--box-shadow) !important;
> }
> 
> .channelTextArea__2e60f.channelTextArea__56a36, .searchBar_e0c60b { /* Message text field and message search bar box shadow */
>     box-shadow: var(--box-shadow);
> }
> 
> .button__4f306.enabled__470f0:hover, .button__66e8c.buttonColor_a6eb73:hover, .withTagAsButton_cc125f:hover { /* Hover background and box shadows on user buttons */
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
> }
> 
> #popout_9007.layer_ec16dd, .overlayBackground__86b78 { /* Box shadow for user profile popout */
>     box-shadow: var(--box-shadow);
> }
> 
> .userPopoutOuter_d739b2 {   /* Box shadow for own user profile */
>     box-shadow: var(--box-shadow);
> }
> 
> /* CHANNELS */
> 
> :root .autocomplete_df266d {   /* Mentions menu background and shadow */ 
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
> }
> 
> .containerDefault__3187b.selected__3b4cb, .containerDefault__3187b.wrapper__7bcde.modeSelected__487d6 { /* Styling for selected channel or thread */
>     box-shadow: var(--box-shadow);
>     background-color: var(--background-tertiary);
>     margin-left: 0;
>     border-left: 4px solid var(--brand-experiment);
>     border-radius: 0 4px 4px 0;
>     margin-right: 8px;
> }
> 
> .wrapper__7bcde:hover .link__95dc0 { /* Styling for hovered channels */
>     margin-right: 8px;
> }
> 
> .selected__9800b.container__4f20e .layout_bb8e67 { /* Styling for selected user in channel */
>     box-shadow: var(--box-shadow);
>     margin-right: 8px;
> }
> 
> .container__4f20e .layout_bb8e67:hover { /* Box shadow for hovered user in channel */
>     margin-right: 8px;
> }
> 
> .browser_fece63 .header__53b07 { /* Styling for Threads popup */
>     background-color: var(--background-primary);
> }
> 
> .searchBox_ff53b2.container__7712a, .container__6604b:hover {
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
>     border: none;
> }
> 
> .container-3i3IzO, .card-PQEqCK, .submitContainer_b4471d .channelTextArea_c27a51.channelTextArea__56a36, div.container_dbadf5 .wrapper_efe67f { /* Styling for threads preview, first message card, and server invites */
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
> }
> 
> .jumpToPresentBar__0ff7f .barButtonMain__0f5c6 {  /* Styling for jump to present bar */
>     display: none;
> }
> 
> .jumpToPresentBar__0ff7f {
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
>     margin-bottom: 16px;
>     padding: 4px;
>     border-radius: 8px;
>     opacity: 1;
>     left: initial;
> }
> 
> .jumpToPresentBar__0ff7f:active {
>     margin-bottom: 15px;
> }
> 
> :root .spoilerContent__37bfa.hidden_f44e41, .markup_a7e664 pre code { /* Styling for code blocks and spoilers */
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
> }
> 
> .markup_a7e664 blockquote, .markup_a7e664 pre {
>     margin-bottom: 5px;
> }
> 
> :root .spoilerContent__37bfa.hidden_f44e41:hover {
>     background-color: var(--background-modifier-hover);
> }
> 
> .newMosaicStyle__8d3be .textContainer__709ff, .newMosaicStyle__8d3be .footer__06f4b, .newMosaicStyle__8d3be .codeView__8b1ff, .attachment_f3cf2c { /* Styling for attachments */
>     border: none;
>     background-color: transparent;
> }
> 
> .attachmentContentItem_ef9fc2, .wrapperAudio__555ce.newMosaicStyle_fb18b9 {
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
>     border-radius: 8px;
>     border: none;
> }
> 
> .hoverButtonGroup__5b423.nonMediaAttachment__30665 {
>     outline: none;
>     top: 8px;
>     right: 8px;
>     background-color: transparent;
> }
> 
> #emoji-picker-tab-panel .searchBar__8f956 { /* Emoji picker search bar */
>     box-shadow: var(--box-shadow);
> }
> 
> .embedFull__8dc21 { /* Styling for embeds */
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
> }
> 
> .wrapper_c727b6, .reaction_fef95b.reactionMe__98f57 { /* Styling for message buttons and reactions */
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
> }
> 
> .wrapper_fbbb73 {   /* Box shadow for "Follow to get this channel's updates in your own server." wrapper */
>     box-shadow: var(--box-shadow);
> }
> 
> .header__60bef, .container__10dc7, .scrollerContainer_bf5dbd, .container__7590f { /* Background color for channel browsing page */
>     background-color: var(--background-primary) !important;
> }
> 
> .search__4a09e.container__7712a.medium__0fb5d, .container__7590f .container__6a848, .optionButtonWrapper__4072c  { /* Styling for channel browsing search bar and cards */
>     background-color: var(--background-tertiary);
>     box-shadow: var(--box-shadow);
>     border: none;
> }
> `
> ```

That fixed it, thank you!

**Comment by TheEvasion** [comment] 2024-03-11 01:32
Same issue. but to the above fix, it changes the font to some off-brand times new roman looking stuff.

**Comment by RockESV** [comment] 2024-06-06 04:22
Hello! This issue was caused by a problem with the GitHub Pages deployment of the source files. It should be fixed now!

**Closed as completed by RockESV** 2024-06-06 04:22 UTC

**Comment by TheEvasion** [comment] 2024-06-08 06:03
ahh my favorite theme is back. preciate it!

**Comment by TheEvasion** [comment] 2024-06-08 06:03
> Hello! This issue was caused by a problem with the GitHub Pages deployment of the source files. It should be fixed now!


ahh my favorite theme is back. preciate it!
